/*
 * MTN SME Hub Redesign, release status (the gate config).
 * Generated by control.html. Committed so gate-links.js can read it on every
 * live page. Edit this file by hand only in an emergency, use Mission
 * Control (control.html, local-only, never committed) so the file always
 * matches what you actually intended.
 *
 * Keys are paths relative to the repo root, e.g. "site/index.html", not bare
 * filenames, the root index.html (this archive hub) and site/index.html
 * (the V1 homepage) share a filename, so a bare-filename key would collide.
 * The root archive hub itself is never gated and has no entry here.
 *
 * Allowed: "finalised" | "under-review" | "under-work" | "not-started"
 * Anything other than "finalised" is treated as hidden on the live site.
 */
window.MOCKUP_STATUS = {
  "site/index.html": "finalised",
  "site/index-v2.html": "finalised",
  "site/index-v3.html": "finalised",
  "site/sales-advisor.html": "finalised",
  "site/sales-advisor-v2.html": "finalised",
  "site/sales-advisor-v3.html": "finalised",
  "site/portal-login.html": "finalised",
  "site/portal-dashboard.html": "finalised",
  "site/contact.html": "finalised",
  "site/business-solutions.html": "finalised",
  "site/product.html": "finalised",
  "site/plan.html": "finalised",
  "site/about.html": "finalised",
  "site/business-advice.html": "finalised",
  "site/category.html": "finalised",
  "site/article.html": "finalised",
  "site/guide.html": "finalised",
  "site/guides.html": "finalised",
  "site/template.html": "finalised",
  "site/templates.html": "finalised",
  "site/insights.html": "finalised",
  "site/event.html": "finalised",
  "site/event-replay.html": "finalised",
  "site/events.html": "finalised",
  "site/stakeholders.html": "finalised",
  "site/brand_ci.html": "finalised",
  "reports/data-and-lead-engine-strategy.html": "finalised",
  "reports/SMEHub-Marketplace-Delivery-Proposal.html": "finalised"
};
window.MOCKUP_STATUS_PUBLISHED = null;
